name = "ga-pick-public"
main = "src/index.js"
compatibility_date = "2026-08-05"

[triggers]
crons = ["0 */6 * * *"]

[vars]
SOLAPI_CHANNEL_ID = "KA01PF260720091629575EzVmd2YRyU7"
SOLAPI_FROM = "01066312323"
SOLAPI_ADMIN_PHONE = "01066312323"
SOLAPI_TEMPLATE_CUSTOMER_QUOTE_RECEIVED = "KA01TP260725102717135cJKdPONLQG6"
SOLAPI_TEMPLATE_CUSTOMER_QUOTE_CLOSED = "KA01TP260725102108064eaQr0cpVqwj"
SOLAPI_TEMPLATE_CUSTOMER_BID_RECEIVED = "KA01TP260725102553611B0oIQcJ0RCF"
SOLAPI_TEMPLATE_ADMIN_SELLER_APPLICATION = "KA01TP2607210300081256MK0cxuHata"
SOLAPI_TEMPLATE_SELLER_BID_SELECTED = "KA01TP260725101805441M3apRU3OCMB"
SOLAPI_TEMPLATE_SELLER_APPROVED = "KA01TP260725101616235ziVJkZImZ9O"
SOLAPI_TEMPLATE_SELLER_REJECTED = "KA01TP260725102900428RYxfTGV9SoG"
SOLAPI_TEMPLATE_SELLER_QUOTE_REGISTERED = "KA01TP260805074550965Bb2zfMAs16w"

[assets]
directory = "./public"
binding = "ASSETS"
html_handling = "none"
not_found_handling = "none"
run_worker_first = ["/", "/index.html", "/quote*", "/my-quote*", "/seller*", "/brand*", "/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "ga-pick-db"
database_id = "32dfadf4-bbd8-440c-b4ed-58fb564c6f06"

[[r2_buckets]]
binding = "FILES"
bucket_name = "ga-pick-files"
