name = "ga-pick-admin"
main = "src/index.js"
compatibility_date = "2026-07-17"

[vars]
SOLAPI_CHANNEL_ID = "KA01PF260720091629575EzVmd2YRyU7"
SOLAPI_FROM = "01066312323"
SOLAPI_ADMIN_PHONE = "01066312323"
SOLAPI_TEMPLATE_CUSTOMER_QUOTE_RECEIVED = "KA01TP260721025042754h4ZUWHp0Vl8"
SOLAPI_TEMPLATE_CUSTOMER_QUOTE_CLOSED = "KA01TP2607210258227887LLx9OshNug"
SOLAPI_TEMPLATE_CUSTOMER_BID_RECEIVED = "KA01TP260721025517053z5NPvs1ZUIX"
SOLAPI_TEMPLATE_SELLER_BID_SELECTED = "KA01TP260721133628815TgDs1sAwUhc"
SOLAPI_TEMPLATE_SELLER_APPROVED = "KA01TP2607211355258674q0EFuag5GE"
SOLAPI_TEMPLATE_SELLER_REJECTED = "KA01TP260723100412983h6pYV7vWwi5"

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "ga-pick-db"
database_id = "32dfadf4-bbd8-440c-b4ed-58fb564c6f06"

[[r2_buckets]]
binding = "FILES"
bucket_name = "ga-pick-files"
